export const defaultSubcategoriesByCategory = {
  Bangles: [
    "Bridal Bangles",
    "Wedding Chura",
    "Couple Name",
    "Kada",
    "Punjabi Chura",
    "Rajwadi Chura",
    "Metal Bangles",
    "Glass Bangles",
    "Lac Bangles",
    "Thread Bangles",
    "Antique/Traditional",
    "Bridal Set",
    "Couple/His-Hers",
    "Minimal/Modern",
    "Men's Kada",
  ],

  Necklaces: [
    "Choker",
    "Pendant",
    "Long Chains",
    "Short Chains",
    "Rani Haar",
    "Layered Necklaces",
    "Collar Necklace",
    "Bib Necklace",
    "Matinee Necklace",
    "Princess Necklace",
    "Opera Necklace",
    "Kundan Necklace",
    "Temple Necklace",
    "Beaded Necklace",
    "Pearl Necklace",
    "Statement Necklace",
    "Adjustable Length",
    "Lockets",
    "Chain with Pendant",
    "Ethnic/Handcrafted Necklaces",
  ],

  Rings: [
    "Engagement Rings",
    "Wedding Bands",
    "Eternity Rings",
    "Promise Rings",
    "Cocktail/Fashion Rings",
    "Signet Rings",
    "Stackable Rings",
    "Adjustable Rings",
    "Gemstone/Stone Rings",
    "Minimal/Plain Rings",
    "Men's Rings",
    "Antique/Vintage Rings",
    "Halo Rings",
    "Cluster Rings",
    "Solitaire Rings",
  ],

  Earrings: [
    "Studs",
    "Hoops",
    "Huggies",
    "Drops",
    "Dangles",
    "Jhumka",
    "Chandbali",
    "Chandelier Earrings",
    "Ear Cuffs",
    "Threader Earrings",
    "Cluster Earrings",
    "Tassel Earrings",
    "Clip-ons",
    "Statement Earrings",
    "Minimal/Everyday Earrings",
  ],

  "Hair Accessories": [
    "Maang Tikka / Matha Patti",
    "Hair Clips & Barrettes",
    "Hair Bands / Headbands",
    "Gajra & Flower Accessories",
    "Bun Pins & Bun Covers",
    "Hair Combs",
    "Hair Chains",
    "Hair Extensions (Decorative)",
    "Scrunchies (Decorative)",
    "Bridal Hair Sets",
  ],

  Boxes: [
    "Ring Box",
    "Earring Box",
    "Necklace Box",
    "Bangle Box",
    "Travel Jewellery Case",
    "Gift Box",
    "Organizer Tray / Insert",
    "Stackable Boxes",
    "Watch & Jewellery Combo Box",
    "Luxury Hinged Jewellery Box",
  ],

  Other: [
    "Anklets",
    "Toe Rings",
    "Nose Rings / Nath",
    "Men's Accessories (Cufflinks, Tie Pins)",
    "Brooches & Pins",
    "Care & Cleaning Kits",
    "Custom / Personalized Jewellery",
    "Kaleera"
  ],
};

export function getDefaultSubcategoriesFor(mainCategory) {
  return defaultSubcategoriesByCategory[mainCategory] || [];
}
